version: '2.2'
services:
  java-resources-optimization:
    image: java:openjdk-8u91
    hostname: "java-resources-optimization.dev"
    container_name: java-resources-optimization
    volumes:
      - ./:/app/
    working_dir: /app/
    command: tail -f /dev/null
    mem_limit: 150m
    cpus: 0.5
    memswap_limit: 0
    network_mode: bridge
